{{- /*
  Paperless secret
*/}}
{{- if not .Values.paperless.secretKey.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.secrets.general" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: paperless-ngx
    {{- include "paperless.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: Opaque
data:
  secretKey: {{ include "paperless.secretkey" . | b64enc | quote }}
{{- end }}
---
{{- /*
  Admin secret
*/}}
{{- if not .Values.paperless.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.secrets.admin" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: paperless-ngx
    {{- include "paperless.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: "kubernetes.io/basic-auth"
data:
  username: {{ .Values.paperless.auth.adminUser | b64enc | quote }}
  password: {{ .Values.paperless.auth.adminPassword | b64enc | quote }}
{{- end }}
---
{{- /*
  Redis secret
*/}}
{{- if not .Values.paperless.redis.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.secrets.redis" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: paperless-ngx
    {{- include "paperless.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: Opaque
data:
  uri: {{ include "paperless.redis.uri" . | b64enc | quote }}
{{- end }}
---
{{- /*
  PostgreSQL secret
*/}}
{{- if not .Values.paperless.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.secrets.postgresql" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: paperless-ngx
    {{- include "paperless.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: "kubernetes.io/basic-auth"
data:
  username: {{ .Values.paperless.postgresql.user | b64enc | quote }}
  password: {{ .Values.paperless.postgresql.password | b64enc | quote }}
{{- end }}
---
{{- /*
  SMTP secret
*/}}
{{- if not .Values.paperless.smtp.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.secrets.smtp" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: paperless-ngx
    {{- include "paperless.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: "kubernetes.io/basic-auth"
data:
  username: {{ .Values.paperless.smtp.user | b64enc | quote }}
  password: {{ .Values.paperless.smtp.password | b64enc | quote }}
{{- end }}
---
{{- /*
  Django AllAuth secret
*/}}
{{- if not .Values.paperless.auth.social.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless.secrets.allauth" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: paperless-ngx
    {{- include "paperless.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: Opaque
data:
  accountProviders: {{ .Values.paperless.auth.social.accountProviders | b64enc | quote }}
{{- end }}
