# Copyright Ad Noctem Collective
# SPDX-License-Identifier: MIT

apiVersion: v2
appVersion: 1.30.5
kubeVersion: ">=1.26.0-0"
name: vaultwarden
version: 0.2.3
description: Vaultwarden is an open-source, community-supported, Bitwarden-compatible server written in Rust
home: https://github.com/dani-garcia/vaultwarden
icon: https://github.com/adnoctem/artwork/blob/425046029eaed451f5ced22ddc650059dff11878/projects/vaultwarden/icon/black/vaultwarden-icon-black.png
keywords:
  - passwords
  - password-manager
  - bitwarden
  - keepass
  - vaultwarden
sources:
  - "https://github.com/adnoctem/helm"
maintainers:
  - name: adnoctem
    email: info@adnoctem.co
  - name: MVProwess
    email: info@mvprowess.com
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: 97DB36A8BD5E342076ED46D63E317D513290CC4B
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/97DB36A8BD5E342076ED46D63E317D513290CC4B
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: vaultwarden
      image: docker.io/vaultwarden/server:1.30.5-alpine
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/adnoctem/helm
    - name: Support
      url: https://github.com/adnoctem/helm/issues
    - name: Vaultwarden GitHub Repository
      url: https://github.com/dani-garcia/vaultwarden
    - name: Vaultwarden Documentation
      url: https://github.com/dani-garcia/vaultwarden/wiki
  org.opencontainers.image.vendor: "Ad Noctem Collective"
  org.opencontainers.image.licenses: "MIT"
  # ref: https://artifacthub.io/docs/topics/annotations/helm/
  artifacthub.io/changes: |
    - kind: fixed
      description: add missing namespace references
    - kind: added
      description: volumes and volumeMounts configuration within values.yaml
    - kind: changed
      description: updated values.schema.json
